...

diff --git a/libexec/hsenv b/libexec/hsenv
--- a/libexec/hsenv
+++ b/libexec/hsenv
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# nodenv version
+# hsenv version
 version="0.3.3"
 
 # Bomb out if we hit an error, ever
@@ -8,7 +8,7 @@ set -e
 export -n CDPATH
 
 # Verbose output in debug mode
-[ -n "$NODENV_DEBUG" ] && {
+[ -n "$HSENV_DEBUG" ] && {
   set -x
 }
 
@@ -31,31 +31,31 @@ abs_dirname() {
   cd "$cwd"
 }
 
-# Set up NODENV_ROOT, location where everything lives
+# Set up HSENV_ROOT, location where everything lives
 
-if [ -z "${NODENV_ROOT}" ]; then
-  NODENV_ROOT="${HOME}/.nodenv"
+if [ -z "${HSENV_ROOT}" ]; then
+  HSENV_ROOT="${HOME}/.hsenv"
 else
-  NODENV_ROOT="${NODENV_ROOT%/}"
+  HSENV_ROOT="${HSENV_ROOT%/}"
 fi
 
-export NODENV_ROOT
+export HSENV_ROOT
 
-# Jump into the NODENV_DIR
-if [ -z "${NODENV_DIR}" ]; then
-  NODENV_DIR="$(pwd)"
+# Jump into the HSENV_DIR
+if [ -z "${HSENV_DIR}" ]; then
+  HSENV_DIR="$(pwd)"
 else
-  cd "${NODENV_DIR}" 2>/dev/null || {
-    echo "nodenv: cannot change working directory to \`$NODENV_DIR'"
+  cd "${HSENV_DIR}" 2>/dev/null || {
+    echo "hsenv: cannot change working directory to \`$HSENV_DIR'"
     exit 1
   } >&2
 
-  NODENV_DIR="$(pwd)"
+  HSENV_DIR="$(pwd)"
 
   cd "$OLDPWD"
 fi
 
-export NODENV_DIR
+export HSENV_DIR
 
 # Pop the first argument, our subcommand
 command="$1"
@@ -66,19 +66,19 @@ export PATH="${bin_path}":$PATH
 
 case "$command" in
   "" | "-h" | "--help" )
-    exec nodenv-help
+    exec hsenv-help
     ;;
 
   "-v" | "--version" )
-    echo "nodenv ${version}"
+    echo "hsenv ${version}"
     exit
     ;;
 
   *)
-    command_path="${bin_path}/nodenv-${command}"
+    command_path="${bin_path}/hsenv-${command}"
 
     [ -x "${command_path}" ] || {
-      echo "nodenv: no such command \`$command'" >&2
+      echo "hsenv: no such command \`$command'" >&2
       exit 1
     }
 
diff --git a/libexec/hsenv-global b/libexec/hsenv-global
--- a/libexec/hsenv-global
+++ b/libexec/hsenv-global
@@ -2,24 +2,24 @@
 #
 # Summary: Persist the preferred NodeJS default version.
 #
-# Usage: nodenv global <version>
-#        nodenv global --unset|-u
+# Usage: hsenv global <version>
+#        hsenv global --unset|-u
 
 # Bomb out if we hit an error, ever
 set -e
 
 # Verbose output in debug mode
-[ -n "$NODENV_DEBUG" ] && {
+[ -n "$HSENV_DEBUG" ] && {
   set -x
 }
 
 # Set the version
 version="$1"
-version_file="${NODENV_ROOT}/version"
+version_file="${HSENV_ROOT}/version"
 
 case "$version" in
   "")
-    echo "nodenv: a version or --unset is required" >&2
+    echo "hsenv: a version or --unset is required" >&2
     exit 1
     ;;
 
@@ -28,7 +28,7 @@ case "$version" in
       rm "$version_file"
       echo "Unset $version_file"
     else
-      echo "nodenv: no global version to unset" >&2
+      echo "hsenv: no global version to unset" >&2
       exit 1
     fi
     ;;
diff --git a/libexec/hsenv-local b/libexec/hsenv-local
--- a/libexec/hsenv-local
+++ b/libexec/hsenv-local
@@ -2,14 +2,14 @@
 #
 # Summary: Persist the preferred NodeJS version in the cwd.
 #
-# Usage: nodenv local <version>
-#        nodenv local --unset|-u
+# Usage: hsenv local <version>
+#        hsenv local --unset|-u
 
 # Bomb out if we hit an error, ever
 set -e
 
 # Verbose output in debug mode
-[ -n "$NODENV_DEBUG" ] && {
+[ -n "$HSENV_DEBUG" ] && {
   set -x
 }
 
@@ -18,7 +18,7 @@ version="$1"
 
 case "$version" in
   "")
-    echo "nodenv: a version or --unset is required" >&2
+    echo "hsenv: a version or --unset is required" >&2
     exit 1
     ;;
 
@@ -30,7 +30,7 @@ case "$version" in
       rm "$(pwd)/.nvm-version"
       echo "Unset local .nvm-version file"
     else
-      echo "nodenv: no local version to unset" >&2
+      echo "hsenv: no local version to unset" >&2
       exit 1
     fi
     ;;
